### PR TITLE
Replace set for listing keys with `KEYS`

### PR DESCRIPTION
**Pull request by bkeepers**
Setting a lot of keys with a TTL quickly fills up the `namespace:keyv` set with key names that no longer exist. If these keys never get read again, they will stay stored in redis indefinitely.

This replaces the `namespace:keyv` set with a call to `KEYS keyv:*` to get a list of keys that are currently set.

cc @wilhelmklopp

### CODE REVIEW

**Comment by lukechilds** [comment]
Thanks for taking the time to put this together.

I intentionally avoided using `KEYS` because it blocks the whole Redis instance while it is scanning the entire data set. Keyv is supposed to be a general purpose cache/key-value store, it's not safe to make the assumption that it's safe to lock up the data set.

Using a set to store your keys and scanning that is a common alternative pattern which is much more suited to production use and endorsed by the official Redis docs.

While it's not ideal that keys are stored in the set after they've expired, the actual key-value data isn't, just the reference to the key. This should only be a tiny amount of data and is IMO a good trade off compared to locking up the data set.

Sources:

>Applications should never use the KEYS commands to retrieve data. KEYS blocks the whole Redis instance while it is scanning linearly the millions of keys you have stored. It is more a debugging command supposed to be used in administration tools.
>
>With Redis, there is no btree structure to index the keys, so you cannot query for keys, except if your keys are stored in an existing collection (set, zset, etc ...)

https://stackoverflow.com/questions/8744207/finding-keys-using-wildcards

>**Warning:** consider KEYS as a command that should only be used in production environments with extreme care. It may ruin performance when it is executed against large databases. This command is intended for debugging and special operations, such as changing your keyspace layout. Don't use KEYS in your regular application code. If you're looking for a way to find keys in a subset of your keyspace, consider using SCAN or sets.

https://redis.io/commands/keys

**Comment by lukechilds** [comment]
>While it's not ideal that keys are stored in the set after they've expired, the actual key-value data isn't, just the reference to the key. This should only be a tiny amount of data and is IMO a good trade off compared to locking up the data set.

Sorry, just read your https://github.com/integrations/slack/pull/448 issue. So it seems like the key references *are* a big enough to cause issues, at least in your scenario.

What are your opinions on using `KEYS`? It seems from the documentation I've read (linked above) that this is pretty heavily recommended against. But I definitely don't want to be causing memory leaks by filling Redis with references to stale keys either.

I'm open to merging this in if you can prove that using `KEYS` isn't as big of an issue as the docs make out, or suggest an alternative solution that doesn't block.

**Comment by lukechilds** [comment]
After doing a bit of digging, it seems like the ideal solution would be to be able to give `SADD` a ttl so it can auto expire items from the set, however that isn't possible.

As far as I can tell we have three options:

**1. Store key references in a set (current behaviour)**

Works fast and doesn't block, however in the specific use case of using a large amount of single use ttl keys it will full up the set with stale keys leading to excessive memory use over time.

**2. Don't store key references and just scan them with `KEYS`**

Works well for normal read/writes, however if you need to do a `keyv.clear()` it will lock the entire Redis data set. This probably won't be a huge issue for smaller applications but for large applications could completely kill performance. Remember it's not just locking Keyv, it's locking the entire Redis dataset.


**3. Don't store key references and just scan them with `SCAN`**

Basically the same as `KEYS`, however we have to iterate over chunks of the dataset in multiple calls. This has the benefit of not locking the entire dataset, with the downside of not guaranteeing to return reliable data because the dataset may change as we're iterating over chunks.

AKA `keyv.clear()` isn't guaranteed to actually clear all the keys.

>Since these commands allow for incremental iteration, returning only a small number of elements per call, they can be used in production without the downside of commands like KEYS or SMEMBERS that may block the server for a long time (even several seconds) when called against big collections of keys or elements.
>
>However while blocking commands like SMEMBERS are able to provide all the elements that are part of a Set in a given moment, The SCAN family of commands only offer limited guarantees about the returned elements since the collection that we incrementally iterate can change during the iteration process.

https://redis.io/commands/scan

**Comment by bkeepers** [comment]
Storing data in a set was causing a pretty steady increase in memory usage of 2-3MB per day for us:

redis-cylindrical-76270___heroku_data

You can see ☝️ when we deployed this branch to production and deleted the `namespace:keyv` set.

All of the data we store in Redis currently has a 30 min TTL. It's only read if further activity occurs within that 30 min (e.g. an issue or comment is updated, PR statuses update, the same link is shared in the same channel, etc).

How often is `clear` used in production environments? We only use it for testing and occasionally for resetting data when things have gone awry. I'm personally willing to accept the tradeoff of locking up the entire instance when calling `KEYS`, but I'm sure other people have different use cases.

**Comment by lukechilds** [comment]
I tend to agree with your reasoning. `clear` is probably not likely to be used that much, and preventing a (circumstantial) memory leak in exchange for locking up the data set in a (possibly) occasional scenario seems reasonable in most cases. However like you say, this could be a massive issue for other use cases. I don't know how everyone is using Keyv so I want to be very careful before changing this behaviour.

The major downside is I've put a lot of effort into Keyv and the official storage adapters to make sure the transition is seamless. AKA you can swap out `@keyv/redis` for `@keyv/postgres` and it will behave exactly the same.

The will break that behaviour because `clear` doesn't block with any of the other storage adapters.

What are your opinions on the `SCAN` solution?

**Comment by lukechilds** [comment]
Another possible solution would be to implement all three methods and allow the user to choose which one is relevant to their use case.

Although that adds a lot of complexity and maintenance overhead to `@keyv/redis`. If there is a more robust way to deal with this scenario I'd much rather use that.

I've got Twitter on the case: https://twitter.com/sindresorhus/status/974151154039906304

**Comment by smithamax** [comment]
> AKA `keyv.clear()` isn't guaranteed to actually clear all the keys.

Just to be clear, the SCAN solution will delete all the keys that existed before the scan started. From my understanding it just wont be linearizable.

Basicly
```
keyv.clear();
// somewhere else
keyv.set('key1', 'value1').then(() => keyv.set('key2', 'value2'));
```
You would expect the `clear()` to happen before, between or after the `set()`s

But with scan you could be left with value1 set but have value2 deleted if the scan starts before both `set()`s and finishes after both.

Personally I'd err I the side it being linearizable over performant. Having a latency spike would be much easier to debug than a very obscure consistency issue.

> Another possible solution would be to implement all three methods and allow the user to choose which one is relevant to their use case.

I'd ditch the current reference method altogether, unless you use [transactions](https://redis.io/topics/transactions) it's going to have a bunch of consistency problems.

**Comment by lukechilds** [comment]
>Personally I'd err on the side it being linearizable over performant. Having a latency spike would be much easier to debug than a very obscure consistency issue.

Agreed

>I'd ditch the current reference method altogether

Are you referring to the reference method as the one currently in use or the one proposed in this PR?

**Comment by smithamax** [comment]
> Are you referring to the reference method as the one currently in use or the one proposed in this PR?
The one currently in use.

**Comment by itamarhaber** [comment]
Strictly Redis-wise speaking:
1. Don't use `KEYS`. Ever. Period. (at least until an upcoming version changes the current behavior)
2. `SCAN`ning is an alternative but has limitations (as noted above) and isn't meant for real-time use.
3. Keyspace notifications on expiry events are great, but if you can't depend on delivery as PubSub is shoot and forget.
4. I would consider managing expiration "manually" - using a sorted set to store key names and their expiration timestamp as score, and periodically querying it to remove elements and keys that have expired.

**Comment by lukechilds** [comment]
@itamarhaber thanks, I really appreciate you taking the time to chime in on this. For those who aren't aware, @itamarhaber works at [Redis Labs](https://redislabs.com/) so he knows his stuff.

To make sure I'm understanding your proposal, you're saying you think the best solution would be similar to the current solution of storing key references in a set. However instead use a sorted set that also stores the TTL as the score. (or more accurate an expire timestamp calculated from the TTL).

On regular intervals we would then fetch all the expired items in the set. We could do this efficiently by passing the current timestamp to `ZRANGE` and getting all elements with a score higher than the timestamp. Then remove all of those elements from the sorted set with `ZREM`.

Is that correct?

This sounds like a good solution. Once potential issue I can think of would be that in between the execution `ZRANGE` and `ZREM` a key could be updated with a new TTL. So although `ZRANGE` says it's stale, by the time we execute `ZREM` it could have it's TTL updated and no longer be stale. What are your thoughts on this?

**Comment by itamarhaber** [comment]
@lukechilds your above is totally correct, including the reservations wrt "staleness". Also, "if you can use the result of one command..." - no, you can't.

The way I'd address staleness: after doing `ZRANGEBYSCORE`, iterate the results but instead of `DEL`ing them, call a Lua script that a) verifies that the score hadn't changed and b) performs the deletion. Perhaps something like this (untested):

```lua
local zset = KEYS[1]
local target = KETS[2]
local ts = tonumber(ARGV[1])

local cts = tonumber(redis.call('ZSCORE', zset, target))
if ts == cts then
    redis.call('DEL', target)
end
```

That said, in a clustered Redis, the script will not work in most cased due to cross shard violations. If that's an issue, we'll need another more complex solution :) Can someone tell what the original purpose of `namespace:keyv` is?

**Comment by lukechilds** [comment]
>That said, in a clustered Redis, the script will not work in most cased due to cross shard violations.

Unfortunately cluster support is definitely a requirement. Keyv is being used a lot in the wild and I have no idea what Redis configurations people might be using.

>Can someone tell what the original purpose of `namespace:keyv` is?

Keyv is designed to be not just a key-value interface for apps but also embeddable inside third party modules to easily add cache support that works with multiple databases.
https://github.com/lukechilds/keyv#add-cache-support-to-your-module

`namespace:keyv` is the default set used to store application keys. If you were also using two third party modules that used Keyv for caching, they would have their own namespace. So there would be three sets, `namespace:keyv` for your app keys and `foomodule:keyv` and `barmodule:keyv` sets for the other modules keys. `barmodule` can reliably and efficiently call `keyv.clear()` on it's instance of Keyv which will return all the keys in it's set ensuring it only clears it's own namespace.

**Comment by lukechilds** [comment]
@itamarhaber @smithamax got a comment from @antirez on Twitter and it seems like `SCAN` will be adequate:

https://twitter.com/antirez/status/975663220362022912

Thoughts?

**Comment by bkeepers** [comment]
👍 seems good to me.

**Comment by itamarhaber** [comment]
YOLO! JK OC, LGTM :)

**Comment by bkeepers** [comment]
I'm going to close this because I don't plan on pushing it forward.

**Pull request closed without merging**
