### PR TITLE
Update ioredis to ~4.16.0

### PR DESCRIPTION
**Pull request by Kikobeats**

### CODE REVIEW

**Comment by Kikobeats** [comment]
@lukechilds can you merge this?

**Comment by lukechilds** [comment]
Sorry for the delay @Kikobeats.

**Comment by Kikobeats** [comment]
np 🙂 remember needs to release an npm publish!

**Comment by lukechilds** [comment]
What's the need for this update?

Is it fixing a bug or just a perf thing? Changing behaviour in any way?

Just need to know if I should do a SemVer major/minor/patch update.

**Comment by Kikobeats** [comment]
it's just a patch (in my case to have the same `ioredis` version and dedupe it from node_modules)

**Comment by Kikobeats** [comment]
I resoted the branch until you release the version; I'm actually using it 🙂

**Comment by lukechilds** [comment]
@Kikobeats published `@keyv/redis@2.1.1`.

**Pull request merged**
